import Head from 'next/head'
import Image from 'next/image'
import { Roboto_Flex } from 'next/font/google'
import styles from '@/styles/Home.module.scss'

const robo = Roboto_Flex({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${robo.className}`}>
          <h1>Hi, I am Baily</h1>
          <nav>
            <a href="#about">
              <h2>About</h2>
              <p>Learn about me and the hats I wear</p>
            </a>
            <a href="#portfolio">
              <h2>Portfolio</h2>
              <p>Take a look at the things I've done</p>
            </a>
            <a href="#printing">
              <h2>3D Printing</h2>
              <p>Model design and plastic extruding</p>
            </a>
            <a href="#connect">
              <h2>Connect</h2>
              <p>Let's chat</p>
            </a>
          </nav>
      </main>
    </>
  )
}
