import Head from 'next/head'
import Image from 'next/image'
import { Red_Rose } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import React, { useState, useEffect, useRef } from 'react';
import Link from 'next/link';
import {gsap} from 'gsap';
import ScrollTrigger from "gsap/dist/ScrollTrigger";
import { useRouter } from 'next/router';
gsap.registerPlugin(ScrollTrigger);

const rose = Red_Rose({ subsets: ['latin'] })

export default function Home() {
  const NavRef = useRef(null);
  console.log("Home render");

  useEffect(()=>{
    if(NavRef.current){
      console.log('call animateNav',NavRef.current);
      const tl = animateNav();
      console.log(tl);
    }
  },[])

  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <main className={`${styles.main} ${rose.className}`}>
          <div className={`${styles.intro}`}>
            <h1>Hi, I am Baily</h1>
            <h2>Welcome to my website</h2>
          </div>
          <nav ref={NavRef}>
            <NavItem
              number={1}
              styles={styles}
              url="/about"
              title="About"
              excerpt="Learn about me and the hats I wear"
              grid_area="1 / 1 / 2 / 2"
            />
            <NavItem 
              number={2}
              styles={styles}
              url="/portfolio"
              title="Portfolio"
              excerpt="Take a look at the things I've done"
              grid_area="1 / 2 / 2 / 3"
            />
            <NavItem 
              number={3}
              styles={styles}
              anchor="/printing"
              title="3D Printing"
              excerpt="Model design and plastic extruding"
              grid_area="2 / 1 / 3 / 2"
            />
            <NavItem 
              number={4}
              styles={styles}
              anchor="/connect"
              title="Connect"
              excerpt="Let's chat"
              grid_area="2 / 2 / 3 / 3"
            />
          </nav>
      </main>
    </>
  )
}
const NavItem = (props) => {
  const router = useRouter();

  const linkRef = useRef(null);
  const BoxTop = useRef(null);
  const BoxRight = useRef(null);
  const BoxBottom = useRef(null);
  const BoxLeft = useRef(null);

  console.log(props);
  useEffect(() => {
    const viewport = {
      'width' : window.innerWidth,
      'height' : window.innerHeight
    }
    const boxport = {
      'width' : document.querySelector('nav > a').clientWidth,
      'height' : document.querySelector('nav > a').clientHeight,
    }

    return () => {
      console.log("unmount");
      //tl.destroy();
    }
  },[]);

  const handleClick = (event, props) => {
    console.log("handleClick",event,props);
    event.preventDefault();
    navItemToPageAnimation(props.number);
  }

  function navItemToPageAnimation(number){
    // const tl = gsap.timeline({
    //   duration: 0
    // });
    // tl.to([BoxTop.current,BoxRight.current,BoxLeft.current,BoxBottom.current], {
    //   opacity:0.25,
    // }, 'first');
    // tl.fromTo(
    //   linkRef.current,
    //   {
    //     borderLeftWidth: `0px`,
    //     borderRightWidth: `0px`,
    //     borderBottomWidth: `0px`,
    //     borderTopWidth: `0px`,
    //   },
    //   {
    //     borderLeftWidth: padding,
    //     borderRightWidth: padding,
    //     borderBottomWidth: padding,
    //     borderTopWidth: padding,
    //   }, 'first'
    // );
    // tl.fromTo(
    //   linkRef.current,
    //   {
    //     paddingTop: `calc(var(--padding) * 2)`,
    //     paddingBottom: `calc(var(--padding) * 2)`,
    //     paddingLeft: `calc(var(--padding) * 2)`,
    //     paddingRight: `calc(var(--padding) * 2)`,
    //   },
    //   {
    //     paddingTop: `calc(var(--padding) * 1)`,
    //     paddingBottom: `calc(var(--padding) * 1)`,
    //     paddingLeft: `calc(var(--padding) * 1)`,
    //     paddingRight: `calc(var(--padding) * 1)`,
    //   }, 'first'
    // );
    [BoxTop.current, BoxRight.current, BoxLeft.current, BoxBottom.current].forEach((box) => {
      if (box) {
        box.style.opacity = '0'; // Set final opacity
      }
    });
    
    // Set border widths
    if (linkRef.current) {
      linkRef.current.style.borderWidth = `var(--padding)`;
      linkRef.current.style.padding = `calc(var(--padding) * 1)`;
      
      const viewportWidth = window.innerWidth;
      const viewportHeight = window.innerHeight;
  
      // Get the element's bounding rectangle and dimensions
      const rect = linkRef.current.getBoundingClientRect();
      const elementWidth = rect.width;
      const elementHeight = rect.height;
  
      // Calculate the target center position
      const targetX = (viewportWidth - elementWidth) / 2 - rect.left;
      const targetY = (viewportHeight - elementHeight) / 2 - rect.top;
  
      const tl = gsap.timeline({
        duration:0.25
      });
      tl.to(linkRef.current,{
        x:targetX,
        y:targetY,
        scaleX: -1
      }, 0);
      tl.to(linkRef.current.querySelectorAll('*'), {
        opacity:0,
        duration:0
      }, '<');
    }
    
  }

  return (
    <>
      <Link 
        ref={linkRef}
        href={'#'} 
        data-num={props.number} 
        style={{gridArea:props.grid_area}}
        onClick={(e) => handleClick(e,props)}
      >
        <h2>{props.title}</h2>
        <p>{props.excerpt}</p>
      </Link>
      <div ref={BoxTop} data-num={props.number} className={`${props.styles["shadowBox"]} ${props.styles["shadowBox-top"]}`} style={{ gridArea: props.grid_area }}></div>
      <div ref={BoxRight} data-num={props.number} className={`${props.styles["shadowBox"]} ${props.styles["shadowBox-right"]}`} style={{ gridArea: props.grid_area }}></div>
      <div ref={BoxBottom} data-num={props.number} className={`${props.styles["shadowBox"]} ${props.styles["shadowBox-bottom"]}`} style={{ gridArea: props.grid_area }}></div>
      <div ref={BoxLeft} data-num={props.number} className={`${props.styles["shadowBox"]} ${props.styles["shadowBox-left"]}`} style={{ gridArea: props.grid_area }}></div>
    </>
  )
}

const animateNav = () =>{
  const dur = 0.25;
  let tl = gsap.timeline({
    paused:true,
    scrollTrigger: {
      markers:true,
      trigger: "main",
      pin: false, // pin the trigger element while active
      start: "top+=25% 25%", // when the top of the trigger hits the top of the viewport
      end: "top+=50% 10%", // end after scrolling 500px beyond the start
      scrub: 1, // smooth scrubbing, takes 1 second to "catch up" to the scrollbarx
    },
  });

  const Boxes1 = document.querySelectorAll('nav > div[data-num="1"]');
  const Boxes2 = document.querySelectorAll('nav > div[data-num="2"]');
  const Boxes3 = document.querySelectorAll('nav > div[data-num="3"]');
  const Boxes4 = document.querySelectorAll('nav > div[data-num="4"]');
  ///Top
  if(!Boxes1[0].classList.contains('animated')){
    Boxes1[0].classList.add('animated');
    Boxes1[0].style.placeSelf = 'start end';
    tl.add(gsap.fromTo(Boxes1[0], 
      { 
        width:`0%`,
        //translate:`-${box_offset.left}px -${box_offset.top}px`,
      },
      { 
        width: `100%`, 
        //translate:`0px 0px`,
        ease:'none',
      }
    ), 'top',
    );
  }
  if(!Boxes2[0].classList.contains('animated')){
    Boxes2[0].classList.add('animated');
    Boxes2[0].style.placeSelf = 'start start';
    tl.add(gsap.fromTo(Boxes2[0], 
      { 
        width:`0%`,
        //translate:`${0}px -${box_offset.top}px`,
      },
      { 
        width: `100%`,
        //translate:`0px 0px`,
        ease:'none',
      }
    ), 'top'
    );
  }
  //Top Sides
  if(!Boxes1[3].classList.contains('animated')){
    Boxes1[3].classList.add('animated');
    Boxes1[3].style.placeSelf = 'start start';
    tl.add(gsap.fromTo(Boxes1[3], 
      { 
        height:`0%`,
        //translate:`${0}px -${box_offset.top}px`,
      },
      { 
        height: `100%`,
        //translate:`0px 0px`,
        ease:'none',
      }
    ), 'top-side'
    );
  }
  if(!Boxes2[1].classList.contains('animated')){
    Boxes2[1].classList.add('animated');
    Boxes2[1].style.placeSelf = 'start end';
    tl.add(gsap.fromTo(Boxes2[1], 
      { 
        height:`0%`,
        //translate:`${0}px -${box_offset.top}px`,
      },
      { 
        height: `100%`,
        //translate:`0px 0px`,
        ease:'none',
      }
    ), 'top-side'
    );
  }
  //Bottom-side
  if(!Boxes3[3].classList.contains('animated')){
    Boxes3[3].classList.add('animated');
    Boxes3[3].style.placeSelf = 'start start';
    tl.add(gsap.fromTo(Boxes3[3], 
      { 
        height:`0%`,
        //translate:`${0}px -${box_offset.top}px`,
      },
      { 
        height: `100%`,
        //translate:`0px 0px`,
        ease:'none',
      }
    ), 'bottom-side'
    );
  }
  if(!Boxes4[1].classList.contains('animated')){
    Boxes4[1].classList.add('animated');
    Boxes4[1].style.placeSelf = 'start end';
    tl.add(gsap.fromTo(Boxes4[1], 
      { 
        height:`0%`,
        //translate:`${0}px -${box_offset.top}px`,
      },
      { 
        height: `100%`,
        //translate:`0px 0px`,
        ease:'none',
      }
    ), 'bottom-side'
    );
  }
  //Bottom
  if(!Boxes3[2].classList.contains('animated')){
    Boxes3[2].classList.add('animated');
    Boxes3[2].style.placeSelf = 'end start';
    tl.add(gsap.fromTo(Boxes3[2], 
      { 
        width:`0%`,
        //translate:`${0}px -${box_offset.top}px`,
      },
      { 
        width: `100%`,
        //translate:`0px 0px`,
        ease:'none',
      }
    ), 'bottom'
    );
  }
  if(!Boxes4[2].classList.contains('animated')){
    Boxes4[2].classList.add('animated');
    Boxes4[2].style.placeSelf = 'end end';
    tl.add(gsap.fromTo(Boxes4[2], 
      { 
        width:`0%`,
        //translate:`${0}px -${box_offset.top}px`,
      },
      { 
        width: `100%`,
        //translate:`0px 0px`,
        ease:'none',
      }
    ), 'bottom'
    );
  }
  //inner
  if(!Boxes1[1].classList.contains('animated')){
    Boxes1[1].classList.add('animated');
    Boxes1[1].style.width ='5px';
    Boxes1[1].style.placeSelf = 'start end';    tl.add(gsap.fromTo(Boxes1[1], 
      { 
        height:`0%`,
        //translate:`${0}px -${box_offset.top}px`,
      },
      { 
        height: `100%`,
        //translate:`0px 0px`,
        ease:'none',
      }
    ), 'inner'
    );
    tl.add(gsap.fromTo(Boxes1[1], 
      { 
        width:'5px'
        //translate:`${0}px -${box_offset.top}px`,
      },
      { 
        width:'10px',
        //translate:`0px 0px`,
        ease:'none',
      }
    ), 'gap'
    );
  }
  if(!Boxes1[2].classList.contains('animated')){
    Boxes1[2].classList.add('animated');
    Boxes1[2].style.placeSelf = 'end start';
    Boxes1[2].style.height = '5px';
    tl.add(gsap.fromTo(Boxes1[2], 
      { 
        width:`0%`,
        //translate:`${0}px -${box_offset.top}px`,
      },
      { 
        width: `100%`,
        //translate:`0px 0px`,
        ease:'none',
      }
    ), 'inner'
    );
    tl.add(gsap.fromTo(Boxes1[2], 
      { 
        height:'5px'
        //translate:`${0}px -${box_offset.top}px`,
      },
      { 
        height:'10px',
        //translate:`0px 0px`,
        ease:'none',
      }
    ), 'gap'
    );
  }
  if(!Boxes2[3].classList.contains('animated')){
    Boxes2[3].classList.add('animated');
    Boxes2[3].style.placeSelf = 'start start';
    Boxes2[3].style.width ='5px';
    tl.add(gsap.fromTo(Boxes2[3], 
      { 
        height:`0%`,
        //translate:`${0}px -${box_offset.top}px`,
      },
      { 
        height: `100%`,
        //translate:`0px 0px`,
        ease:'none',
      }
    ), 'inner'
    );
    tl.add(gsap.fromTo(Boxes2[3], 
      { 
        width:'5px'
        //translate:`${0}px -${box_offset.top}px`,
      },
      { 
        width:'10px',
        //translate:`0px 0px`,
        ease:'none',
      }
    ), 'gap'
    );
  }
  if(!Boxes2[2].classList.contains('animated')){
    Boxes2[2].classList.add('animated');
    Boxes2[2].style.placeSelf = 'end end';
    Boxes2[2].style.height = '5px';
    tl.add(gsap.fromTo(Boxes2[2], 
      { 
        width:`0%`,
        //translate:`${0}px -${box_offset.top}px`,
      },
      { 
        width: `100%`,
        //translate:`0px 0px`,
        ease:'none',
      }
    ), 'inner'
    );
    tl.add(gsap.fromTo(Boxes2[2], 
      { 
        height:'5px'
        //translate:`${0}px -${box_offset.top}px`,
      },
      { 
        height:'10px',
        //translate:`0px 0px`,
        ease:'none',
      }
    ), 'gap'
    );
  }
  if(!Boxes3[0].classList.contains('animated')){
    Boxes3[0].classList.add('animated');
    Boxes3[0].style.placeSelf = 'start start';
    Boxes3[0].style.height = '5px';
    tl.add(gsap.fromTo(Boxes3[0], 
      { 
        width:`0%`,
        //translate:`${0}px -${box_offset.top}px`,
      },
      { 
        width: `100%`,
        //translate:`0px 0px`,
        ease:'none',
      }
    ), 'inner'
    );
    tl.add(gsap.fromTo(Boxes3[0], 
      { 
        height:'5px'
        //translate:`${0}px -${box_offset.top}px`,
      },
      { 
        height:'10px',
        //translate:`0px 0px`,
        ease:'none',
      }
    ), 'gap'
    );
  }
  if(!Boxes3[1].classList.contains('animated')){
    Boxes3[1].classList.add('animated');
    Boxes3[1].style.placeSelf = 'end end';
    Boxes3[1].style.width ='5px';
    tl.add(gsap.fromTo(Boxes3[1], 
      { 
        height:`0%`,
        //translate:`${0}px -${box_offset.top}px`,
      },
      { 
        height: `100%`,
        //translate:`0px 0px`,
        ease:'none',
      }
    ), 'inner'
    );
    tl.add(gsap.fromTo(Boxes3[1], 
      { 
        width:'5px'
        //translate:`${0}px -${box_offset.top}px`,
      },
      { 
        width:'10px',
        //translate:`0px 0px`,
        ease:'none',
      }
    ), 'gap'
    );
  }
  if(!Boxes4[0].classList.contains('animated')){
    Boxes4[0].classList.add('animated');
    Boxes4[0].style.placeSelf = 'start end';
    Boxes4[0].style.height = '5px';
    tl.add(gsap.fromTo(Boxes4[0], 
      { 
        width:`0%`,
        //translate:`${0}px -${box_offset.top}px`,
      },
      { 
        width: `100%`,
        //translate:`0px 0px`,
        ease:'none',
      }
    ), 'inner'
    );
    tl.add(gsap.fromTo(Boxes4[0], 
      { 
        height:'5px'
        //translate:`${0}px -${box_offset.top}px`,
      },
      { 
        height:'10px',
        //translate:`0px 0px`,
        ease:'none',
      }
    ), 'gap'
    );
  }
  if(!Boxes4[3].classList.contains('animated')){
    Boxes4[3].classList.add('animated');
    Boxes4[3].style.placeSelf = 'end start';
    Boxes4[3].style.width ='5px';
    tl.add(gsap.fromTo(Boxes4[3], 
      { 
        height:`0%`,
        //translate:`${0}px -${box_offset.top}px`,
      },
      { 
        height: `100%`,
        //translate:`0px 0px`,
        ease:'none',
      }
    ), 'inner'
    );
    tl.add(gsap.fromTo(Boxes4[3], 
      { 
        width:'5px'
        //translate:`${0}px -${box_offset.top}px`,
      },
      { 
        width:'10px',
        //translate:`0px 0px`,
        ease:'none',
      }
    ), 'gap'
    );
    tl.add(gsap.to('nav', {gap:'1em'}),'gap');
    tl.add(gsap.to('nav a', {opacity:'1'}),'gap');
  }

  //Gap
  if(tl.labels == {}){
    tl.destroy();
  } else {
    //tl.duration(2);
    //tl.play();
  }
  return tl;
}


function getPropertyValue(element, property_name) {
  const styles = getComputedStyle(element);
  return styles.getPropertyValue(property_name).trim();
}